# Generated by Django 3.1.1 on 2020-09-04 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fixlyft_project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_img', models.ImageField(default='default.png', help_text='Please Upload Image in 90x90 pixels size only for better view', upload_to='shop_images')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('rating', fixlyft_project.utils.IntegerRangeField(default=1)),
                ('city_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[7-9][0-9]{9}$')])),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('services', models.CharField(choices=[('0', 'SELECT_SERVICES'), ('Smartphone / Tablet', 'Smartphone / Tablet'), ('Laptop / Pc', 'Laptop / Pc'), ('Gaming Consoles', 'Gaming Consoles')], default=None, max_length=30)),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-premium', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='OfferImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=999)),
                ('offer_img', models.ImageField(default='c.png', help_text='Please upload images in 331x144 pixels only for better view', upload_to='offer_images')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='SmsOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^[7-9][0-9]{9}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('validated', models.BooleanField(default=False, help_text='True if OTP is verified')),
                ('otp_session_id', models.CharField(default='', max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[7-9][0-9]{9}$')])),
                ('device_name', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobileshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fixlyft.mobileshop')),
            ],
        ),
    ]
